/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum8S2;

/**
 *
 * @author arnom
 */
public class Praktikum84S2 extends javax.swing.JFrame {

    /**
     * Creates new form Praktikum84S2
     */
    public Praktikum84S2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NIM2 = new javax.swing.JTextField();
        sort1 = new javax.swing.JTextField();
        NIM4 = new javax.swing.JTextField();
        NIM3 = new javax.swing.JTextField();
        NIM6 = new javax.swing.JTextField();
        NIM7 = new javax.swing.JTextField();
        NIM5 = new javax.swing.JTextField();
        NIM9 = new javax.swing.JTextField();
        NIM10 = new javax.swing.JTextField();
        NIM8 = new javax.swing.JTextField();
        NIM12 = new javax.swing.JTextField();
        NIM13 = new javax.swing.JTextField();
        NIM11 = new javax.swing.JTextField();
        NIM1 = new javax.swing.JTextField();
        sort2 = new javax.swing.JTextField();
        sort3 = new javax.swing.JTextField();
        sort4 = new javax.swing.JTextField();
        sort5 = new javax.swing.JTextField();
        sort7 = new javax.swing.JTextField();
        sort8 = new javax.swing.JTextField();
        sort6 = new javax.swing.JTextField();
        sort9 = new javax.swing.JTextField();
        sort11 = new javax.swing.JTextField();
        sort12 = new javax.swing.JTextField();
        sort13 = new javax.swing.JTextField();
        sort10 = new javax.swing.JTextField();
        ascending = new javax.swing.JRadioButton();
        decending = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Setelah Sortir");

        NIM2.setForeground(new java.awt.Color(0, 0, 0));
        NIM2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort1.setForeground(new java.awt.Color(0, 0, 0));
        sort1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM4.setForeground(new java.awt.Color(0, 0, 0));
        NIM4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM3.setForeground(new java.awt.Color(0, 0, 0));
        NIM3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM6.setForeground(new java.awt.Color(0, 0, 0));
        NIM6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM7.setForeground(new java.awt.Color(0, 0, 0));
        NIM7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM5.setForeground(new java.awt.Color(0, 0, 0));
        NIM5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM9.setForeground(new java.awt.Color(0, 0, 0));
        NIM9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM10.setForeground(new java.awt.Color(0, 0, 0));
        NIM10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM8.setForeground(new java.awt.Color(0, 0, 0));
        NIM8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM12.setForeground(new java.awt.Color(0, 0, 0));
        NIM12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM13.setForeground(new java.awt.Color(0, 0, 0));
        NIM13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM11.setForeground(new java.awt.Color(0, 0, 0));
        NIM11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        NIM1.setForeground(new java.awt.Color(0, 0, 0));
        NIM1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NIM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIM1ActionPerformed(evt);
            }
        });

        sort2.setForeground(new java.awt.Color(0, 0, 0));
        sort2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort3.setForeground(new java.awt.Color(0, 0, 0));
        sort3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort4.setForeground(new java.awt.Color(0, 0, 0));
        sort4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort5.setForeground(new java.awt.Color(0, 0, 0));
        sort5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort7.setForeground(new java.awt.Color(0, 0, 0));
        sort7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort8.setForeground(new java.awt.Color(0, 0, 0));
        sort8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort6.setForeground(new java.awt.Color(0, 0, 0));
        sort6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort9.setForeground(new java.awt.Color(0, 0, 0));
        sort9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort11.setForeground(new java.awt.Color(0, 0, 0));
        sort11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort12.setForeground(new java.awt.Color(0, 0, 0));
        sort12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort13.setForeground(new java.awt.Color(0, 0, 0));
        sort13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sort10.setForeground(new java.awt.Color(0, 0, 0));
        sort10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonGroup1.add(ascending);
        ascending.setForeground(new java.awt.Color(0, 0, 0));
        ascending.setText("Ascending");
        ascending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascendingActionPerformed(evt);
            }
        });

        buttonGroup1.add(decending);
        decending.setForeground(new java.awt.Color(0, 0, 0));
        decending.setText("Decending");
        decending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decendingActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sortir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nomor Induk Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NIM1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ascending, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NIM5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NIM6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NIM7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(decending, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NIM8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NIM13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sort9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sort11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sort12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sort13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIM2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIM1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ascending)
                    .addComponent(decending))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NIM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIM1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int[] nim = new int[13];
        nim[0] = Integer.parseInt(NIM1.getText());
        nim[1] = Integer.parseInt(NIM2.getText());
        nim[2] = Integer.parseInt(NIM3.getText());
        nim[3] = Integer.parseInt(NIM4.getText());
        nim[4] = Integer.parseInt(NIM5.getText());
        nim[5] = Integer.parseInt(NIM6.getText());
        nim[6] = Integer.parseInt(NIM7.getText());
        nim[7] = Integer.parseInt(NIM8.getText());
        nim[8] = Integer.parseInt(NIM9.getText());
        nim[9] = Integer.parseInt(NIM10.getText());
        nim[10] = Integer.parseInt(NIM11.getText());
        nim[11] = Integer.parseInt(NIM12.getText());
        nim[12] = Integer.parseInt(NIM13.getText());
        
        if(ascending.isSelected()){
        ascending(nim);
        } else if (decending.isSelected()){
            decending(nim);
        }
        
        sort1.setText("" + nim[0]);
        sort2.setText("" + nim[1]);
        sort3.setText("" + nim[2]);
        sort4.setText("" + nim[3]);
        sort5.setText("" + nim[4]);
        sort6.setText("" + nim[5]);
        sort7.setText("" + nim[6]);
        sort8.setText("" + nim[7]);
        sort9.setText("" + nim[8]);
        sort10.setText("" + nim[9]);
        sort11.setText("" + nim[10]);
        sort12.setText("" + nim[11]);
        sort13.setText("" + nim[12]);
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sort1.setText(""); 
        sort2.setText("");
        sort3.setText("");
        sort4.setText("");
        sort5.setText("");
        sort6.setText("");
        sort7.setText("");
        sort8.setText("");
        sort9.setText("");
        sort10.setText("");
        sort11.setText("");
        sort12.setText("");
        sort13.setText("");
        
        NIM1.setText(""); 
        NIM2.setText("");
        NIM3.setText("");
        NIM4.setText("");
        NIM5.setText("");
        NIM6.setText("");
        NIM7.setText("");
        NIM8.setText("");
        NIM9.setText("");
        NIM10.setText("");
        NIM11.setText("");
        NIM12.setText("");
        NIM13.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ascendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ascendingActionPerformed

    private void decendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decendingActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ascending(int[] array) {

        for (int i = 0; i < array.length - 1; i++) {
            int min = i;
            for (int j = i + 1; j < array.length; j++) {
                if (array[min] > array[j]) {
                    min = j;
                }
            }

            int temp = array[i];
            array[i] = array[min];
            array[min] = temp;
        }
    }

    private static void decending(int[] array) {

        for (int i = 0; i < array.length - 1; i++) {
            int min = i;
            for (int j = i + 1; j < array.length; j++) {
                if (array[min] < array[j]) {
                    min = j;
                }
            }

            int temp = array[i];
            array[i] = array[min];
            array[min] = temp;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum84S2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum84S2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum84S2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum84S2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum84S2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIM1;
    private javax.swing.JTextField NIM10;
    private javax.swing.JTextField NIM11;
    private javax.swing.JTextField NIM12;
    private javax.swing.JTextField NIM13;
    private javax.swing.JTextField NIM2;
    private javax.swing.JTextField NIM3;
    private javax.swing.JTextField NIM4;
    private javax.swing.JTextField NIM5;
    private javax.swing.JTextField NIM6;
    private javax.swing.JTextField NIM7;
    private javax.swing.JTextField NIM8;
    private javax.swing.JTextField NIM9;
    private javax.swing.JRadioButton ascending;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton decending;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sort1;
    private javax.swing.JTextField sort10;
    private javax.swing.JTextField sort11;
    private javax.swing.JTextField sort12;
    private javax.swing.JTextField sort13;
    private javax.swing.JTextField sort2;
    private javax.swing.JTextField sort3;
    private javax.swing.JTextField sort4;
    private javax.swing.JTextField sort5;
    private javax.swing.JTextField sort6;
    private javax.swing.JTextField sort7;
    private javax.swing.JTextField sort8;
    private javax.swing.JTextField sort9;
    // End of variables declaration//GEN-END:variables
}